---
computations:
  scheduler: parallel
  number_of_processes: 8
  prefer: processes
  pre_dispatch: all
  verbose: 100

time:
  start_time: 2022-08-19T00
  end_time: 2022-08-20T00
  format: "%Y-%m-%dT%H"
  timezone: "Europe/Warsaw"
  time_delta:
    days: 1
    hours: 0
    minutes: 0
    seconds: 0
