---
data:
  res_list:
    path: "./data/res-list.XLSX"
    columns_rename:
      "Lp.": "lp"
      "Rodzaj OZE": "rodzaj"
      "Województwo": "woje"
      "Powiat": "powiat"
      "Moc zainstalowana [MW]": "moc"
    geo:
      country: Poland

  clean_res_list:
    path: "./data/clean_res_list.csv"

  topo_data:
    input_path: "./data/topo"
    output_path: "./data/clean_topo"
    wind_acronym: "Twt"

  wind_turbines:
    output_path: "./data/wind_turbines.parquet"

computations:
  dt:
    minutes: 1
    seconds: 30
  starttime: "2010-02-11 00:00:00"

process:
  process_ure_rse_source: False
  process_topo: False

# Logging
formatters:
  console_format:
    format: "[%(asctime)s %(levelname)s %(name)s] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
    formatter: console_format

root:
  level: INFO
  handlers: ["console"]

version: 1

time:
  starttime: 0
  timezone: "Europe/Warsaw"
