---
version: 1

formatters:
  console_format:
    format: "[%(asctime)s %(levelname)s %(name)s] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
    formatter: console_format

root:
  level: DEBUG
  handlers: ["console"]
