---
process:
  process_ure_rse_source: False
  process_topo: False
  process_add_row_col: False

data:
  output:
    path: "./data/output"
    name_template: "{date}_{unique_id}"
    format: ".parquet"
  
  res_list:
    path: "./data/res-list.XLSX"
    columns_rename:
      "Lp.": "lp"
      "Rodzaj OZE": "rodzaj"
      "Województwo": "woje"
      "Powiat": "powiat"
      "Moc zainstalowana [MW]": "moc"
    geo:
      country: Poland

  # Dataset with longitude/latitude values
  # Fetch from OpenStreetMap
  clean_res_list:
    path: "./data/clean_res_list.csv"

  # Clean res list with dataset with row/col per grid in meteo model
  # Fetch from ICM MeteoAPI
  ure_res_list_rowcol:
    path: "./data/ure_res_list_rowcol.csv"
    types_of_res:
      - "PVA"
      - "WIL"

  topo_data:
    input_path: "./data/topo"
    output_path: "./data/clean_topo"
    wind_acronym: "Twt"

  wind_turbines:
    output_path: "./data/wind_turbines.parquet"
